changelog:
  exclude:
    labels:
      - release
  categories:
    - title: Breaking changes 🛠
      labels:
        - breaking-change
    - title: Exciting new features 🎉
      labels:
        - enhancement
        - task
        - request
    - title: Bug fixes 🔨
      labels:
        - bug
        - nit
    - title: Other changes
      labels:
        - "*"
