language: node_js
node_js:
  - 16
dist: xenial

jobs:
  include:
    - stage: test
      name: "Verify build"
      script:
        - npm install

        # build the entire application
        - npm run build

        # verify lint of the repo
        # - npm run lint
        # Almost every file throws an error right now.
        # Updating this in this PR will conflict with every open PR

        # run all tests
        - npm run test
