[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src https:; script-src https: 'unsafe-inline'; style-src https:; img-src https: data: blob:"

[[headers]]
  for = "/-/*"
  [headers.values]
    cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''
