[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src https:; script-src https: 'unsafe-inline'; style-src https:; img-src https: data: blob:"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()"
    Referrer-Policy = "no-referrer"
    X-Frame-Options = "SAMEORIGIN" always;
    X-Xss-Protection = "1; mode=block" always;
    X-Content-Type-Options = "nosniff" always;

[[headers]]
  for = "/-/*"
  [headers.values]
    cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''
