version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
  otel-collector:
    extends:
      file: ../scripts/observability/docker-compose.yaml
      service: otel-collector
  zipkin:
    extends:
      file: ../scripts/observability/docker-compose.yaml
      service: zipkin
  prometheus:
    extends:
      file: ../scripts/observability/docker-compose.yaml
      service: prometheus