name: Build and Deploy Cloud Admin to Netlify
on:
  push:
    tags:
      - "*"
    branches: ["netlify"]
    paths:
      - ".github/workflows/cloud-admin.yml"
      - "web-admin/**"
      - "web-local/**"
env:
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  NETLIFY_SITE_ID: ${{ fromJSON('["e73ac785-882e-425a-8fc8-5432528bb374","afb26917-7a60-47d9-81dc-c0babbb0d9a9"]')[ startsWith(github.ref, 'refs/tags/v') == 'true' ] }}
  DEPLOY_SITE: ${{ fromJSON('["ui.rilldata.io","ui.rilldata.com"]')[ startsWith(github.ref, 'refs/tags/v') == 'true' ] }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build Cloud Admin
        run: |-
          npm install esbuild
          npm run build -w web-admin

      - name: Deploy ${{ matrix.name }} to Netlify Staging
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: ./web-admin/build
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Cloud-admin ${{ env.GITHUB_REF_NAME }} deployed to ${{ env.DEPLOY_SITE }}"
        timeout-minutes: 1
