name: Build and Test docs
on:
  pull_request:
    paths:
      - ".github/workflows/docs-check.yml"
      - "docs/**"
jobs:
  build:
    strategy:
      matrix:
        name: ["docs"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: NPM Install ${{ matrix.name }}
        run: npm install -w ${{ matrix.name }}
        # https://typicode.github.io/husky/how-to.html#ci-server-and-docker
        env:
          HUSKY: 0

      - name: Build ${{ matrix.name }}
        run: npm run build -w ${{ matrix.name }}
