name: Build and Deploy to Netlify
on:
  push:
    tags:
      - "*"
    branches: ["netlify"]
    paths:
      - ".github/workflows/docs.yml"
      - "docs/**"
      - "enterprise/**"
jobs:
  build:
    strategy:
      matrix:
        name: ["docs", "docs-enterprise"]
        include:
        - name: docs
          site-id: NETLIFY_DOCS_SITE_ID
        - name: docs-enterprise
          site-id: NETLIFY_ENTERPRISE_SITE_ID
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build ${{ matrix.name }}
        run: npm install -w ${{ matrix.name }} && npm run build -w ${{ matrix.name }}

      - name: Deploy ${{ matrix.name }} to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: ./${{ matrix.name }}/dist
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy ${{ matrix.name }} from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets[matrix.site-id] }}
        timeout-minutes: 1
