# This workflow triggers deployment with Rill Cloud helm charts
# Each merge to main branch is build with github sha tag and published to Rill Cloud.
name: Deploy to Rill Cloud
on:
  push:
    tags:
      - "**"
    branches:
      - main
      - cd
env:
  RELEASE: ${{ contains('refs/tags', github.ref_name) }}

jobs:
  release:
    name: Deploy to Rill Cloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.2

      - name: Build & Publish Rill docker image
        run: |-
          go build -o rill cli/main.go

          echo '${{ secrets.DOCKERHUB_PASS }}' | docker login -u '${{ secrets.DOCKERHUB_USER }}' --password-stdin
          docker build -t rilldata/rill-headless:${GITHUB_SHA} .
          docker push rilldata/rill-headless:${GITHUB_SHA}

      - name: Trigger Rill Cloud deployment
        run: |-
          curl -X POST https://api.github.com/repos/rilldata/rill-helm-charts/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.GORELEASER_ACCESS_TOKEN }}" \
          --data '{"event_type": "Deploying Tag: "'"${GITHUB_REF_NAME}"'", "client_payload": { "github_sha": "'"${GITHUB_SHA}"'", "tag": "'"${GITHUB_REF_NAME}"'", "release": "${{ env.RELEASE }}"}}'
