name: Test SQL shared library
on:
  pull_request:
    paths:
      - "sql/**"
      - ".github/workflows/sql-test.yml"

jobs:
  version_increment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          ref: main
          path: main_repo
      - name: Increment patch version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd main_repo/sql
          MAIN_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          cd ../../sql 
          PR_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          if [[ $MAIN_VERSION == $PR_VERSION ]]; then
            mvn validate -Pbump-patch
            gh pr checkout ${{ github.event.pull_request.number }} 
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add pom.xml 
            NEW_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
            git commit -m "SQL version updated to $NEW_VERSION"
            git push
          fi
  librillsql:
    needs: version_increment
    strategy:
      matrix:
        include:
          - os: macos
            arch: amd64
            runner: macos-latest
          - os: linux
            arch: amd64
            runner: ubuntu-latest
          - os: windows
            arch: amd64
            runner: windows-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: "22.1.0"
          java-version: "17"
          components: "native-image"
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: '3.20.3'
      - name: Build native library
        shell: bash
        run: |
          cd sql
          mvn --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn test
          mvn --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn package -Pnative-lib
