name: Check version update on approval
on:
  pull_request_review:
    types:
      - submitted
    paths:
      - "sql/**"
      - ".github/workflows/sql-test.yml"
jobs:
  version_increment:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          ref: main
          path: main_repo
      - name: Increment patch version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd main_repo/sql
          MAIN_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          cd ../../sql 
          PR_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          if [[ $MAIN_VERSION == $PR_VERSION ]]; then
            mvn validate -Pbump-patch
            gh pr checkout ${{ github.event.pull_request.number }} 
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add pom.xml 
            NEW_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
            git commit -m "SQL version updated to $NEW_VERSION"
            git push
          fi