name: Release SQL shared library
on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/sql-release.yml"
      - "sql/**"

jobs:
  librillsql:
    strategy:
      matrix:
        include:
          - os: macos
            arch: amd64
            runner: macos-latest
          - os: linux
            arch: amd64
            runner: ubuntu-latest
#          - os: windows todo fix windows builds, depends on setup-protoc action https://github.com/arduino/setup-protoc/issues/33
#            arch: amd64
#            runner: windows-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: "22.1.0"
          java-version: "17"
          components: "native-image"
#      - name: Install Protoc todo monitor setup-protoc until they support 21.5 https://github.com/arduino/setup-protoc/issues/33
#        uses: arduino/setup-protoc@v1
#        with:
#          repo-token: ${{ secrets.GITHUB_TOKEN }}
#          version: '21.5'
      - name: Authenticate GCS
        uses: google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.RILL_SQL_SA }}"
      - name: Extract Maven project version
        id: maven-version
        shell: bash
        run: |
          cd sql
          echo ::set-output name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
      - name: Build native library
        shell: bash
        run: |
          cd sql
          case "$OSTYPE" in
            darwin*)  PROTOC_ZIP=protoc-21.5-osx-x86_64.zip ;;
            linux*)   PROTOC_ZIP=protoc-21.5-linux-x86_64.zip ;;
            msys*)    PROTOC_ZIP=protoc-21.5-win64.zip ;;
          esac
          curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v21.5/$PROTOC_ZIP
          sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
          sudo unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
          rm -f $PROTOC_ZIP
          mvn --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn test 
          mvn --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn package -Pnative-lib
      - name: Install zip on Windows
        if: matrix.os == 'windows'
        shell: bash
        run: choco install zip -y --force
      - name: Create archive
        shell: bash
        run: |
          rm sql/target/*.txt
          zip -j librillsql-${{ matrix.os }}-${{ matrix.arch }}.zip sql/target/librillsql.* sql/target/graal_isolate.*
      - name: Upload archive
        uses: google-github-actions/upload-cloud-storage@v0
        with:
          path: librillsql-${{ matrix.os }}-${{ matrix.arch }}.zip
          destination: pkg.rilldata.com/rillsql/releases/v${{ steps.maven-version.outputs.version }}
