name: Build and Test web code
on:
  pull_request:
    paths:
      - ".github/workflows/web-test.yml"
      - "web-admin/**"
      - "web-common/**"
      - "web-local/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Filter modified codepaths
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            admin:
              - ".github/workflows/web-test.yml"
              - "web-admin/**"
            local:
              - ".github/workflows/web-test.yml"
              - "web-local/**"
            common:
              - ".github/workflows/web-test.yml"
              - "web-common/**"

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: NPM Install
        run: npm install

      - name: Install browser for UI tests
        run: npx playwright install

      - name: Prettier checks and lint for web common
        if: steps.filter.outputs.common == 'true'
        run: |-
          npx prettier --check "web-common/**/*"
          npm run lint -w web-common -- --quiet

      - name: Prettier checks and lint for web local
        if: steps.filter.outputs.local == 'true'
        run: |-
          npx prettier --check "web-local/**/*"
          npm run lint -w web-local -- --quiet

      - name: Prettier checks and lint for web admin
        if: steps.filter.outputs.admin == 'true'
        run: |-
          npx prettier --check "web-admin/**/*"
          npm run lint -w web-admin -- --quiet

      - name: Build & Test the web local
        if: ${{ steps.filter.outputs.local == 'true' || steps.filter.outputs.common == 'true' }}
        run: |-
          npm run build -w web-local
          npm run test -w web-local

      - name: Build & Test the web admin
        if: ${{ steps.filter.outputs.admin == 'true' || steps.filter.outputs.common == 'true' }}
        run: |-
          npm run build -w web-admin
          npm run test -w web-admin
