name: Web code quality checks
on:
  pull_request:
    paths:
      - ".github/workflows/web-test.yml"
      - "web-admin/**"
      - "web-auth/**"
      - "web-common/**"
      - "web-local/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Filter modified codepaths
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            admin:
              - ".github/workflows/web-test.yml"
              - "web-admin/**"
            auth:
              - ".github/workflows/web-test.yml"
              - "web-auth/**"
            local:
              - ".github/workflows/web-test.yml"
              - "web-local/**"
            common:
              - ".github/workflows/web-test.yml"
              - "web-common/**"

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: NPM Install
        run: npm install
        # https://typicode.github.io/husky/how-to.html#ci-server-and-docker
        env:
          HUSKY: 0

      - name: lint and type checks for web common
        if: steps.filter.outputs.common == 'true'
        run: |-
          npx eslint web-common --quiet
          npm run check -w web-common

      - name: lint and type checks for web local
        if: steps.filter.outputs.local == 'true'
        run: |-
          npx eslint web-local --quiet
          npm run check -w web-local

      - name: lint and type checks for web admin
        if: steps.filter.outputs.admin == 'true'
        run: |-
          npx eslint web-admin --quiet
          npm run check -w web-admin

      - name: lint and type checks for web auth
        if: steps.filter.outputs.auth == 'true'
        run: |-
          npx eslint web-auth --quiet
          npm run check -w web-auth

      - name: type check non-svelte files (with temporary whitelist)
        run: |-
          bash ./scripts/tsc-with-whitelist.sh
