name: Build and Test web code
on:
  pull_request:
    paths:
      - ".github/workflows/web-test.yml"
      - "web-admin/**"
      - "web-common/**"
      - "web-local/**"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        codepath: [web-admin, web-local]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: NPM Install
        run: npm install

      - name: Prettier checks for web
        run: npx prettier --check "${{ matrix.codepath }}/**/*"

      - name: Install browser for UI tests
        run: npx playwright install

      - name: Build the application
        run: npm run build -w ${{ matrix.codepath }}

      - name: Verify lint of the repo
        run: npm run lint -w ${{ matrix.codepath }} -- --quiet

      - name: Run all tests
        run: npm run test -w ${{ matrix.codepath }}
